// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(vergissmeinnicht_coreFFI)
import vergissmeinnicht_coreFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_vergissmeinnicht_core_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_vergissmeinnicht_core_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureVergissmeinnichtCoreInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




public protocol TaskStoreProtocol: AnyObject, Sendable {
    
    /**
     * Hängt eine Annotation an die Task mit `uuid` an. Entry-Zeitstempel = `Utc::now()`.
     */
    func addAnnotation(uuid: String, annotation: String) throws 
    
    /**
     * Fügt einen einzelnen User-Tag hinzu. No-op, falls der Tag bereits existiert.
     */
    func addTag(uuid: String, tag: String) throws 
    
    /**
     * Legt einen neuen Task mit der gegebenen Description an und gibt seine UUID zurück.
     */
    func addTask(description: String) throws  -> String
    
    /**
     * Legt einen neuen Task mit voller Metadaten-Persistierung an: project (raw value),
     * User-Tags und due (Unix-Sekunden). Leere Tags und None/Empty-Project werden
     * nicht geschrieben. Tag-Strings müssen TaskChampion-konform sein
     * (kein Whitespace, kein Operator-Zeichen am Anfang, kein Doppelpunkt darin).
     */
    func addTaskFull(description: String, project: String?, tags: [String], due: Int64?) throws  -> String
    
    /**
     * Markiert die Task mit `uuid` als gelöscht (`Status::Deleted`) und committet.
     * Das Operations-Log bleibt erhalten — kein Purge.
     */
    func deleteTask(uuid: String) throws 
    
    /**
     * Backwards-Compat-Alias für die App: nur Pending, mit Working-Set-IDs.
     */
    func listPending() throws  -> [TaskInfo]
    
    /**
     * Listet alle Tasks (Pending oder optional auch Completed/Recurring).
     * Deleted-Tasks bleiben immer aussen vor.
     *
     * Bei `include_completed = false` wird nur das Working Set durchlaufen — das enthält
     * ausschließlich Pending-Tasks. Recurring-Master und Completed bleiben in diesem
     * Modus unsichtbar; wer sie braucht, muss `include_completed = true` setzen.
     * Bei `true` werden Pending mit `working_set_id` zuerst ausgegeben, danach alle
     * übrigen sichtbaren Status (Completed, Recurring, sowie ggf. Pending ohne
     * Working-Set-Eintrag) — die App sortiert clientseitig.
     */
    func listTasks(includeCompleted: Bool) throws  -> [TaskInfo]
    
    /**
     * Markiert die Task mit `uuid` als erledigt (`Status::Completed`) und committet.
     */
    func markDone(uuid: String) throws 
    
    /**
     * Markiert eine Pending-Task als erledigt und legt — sofern `recur` und
     * `new_due` gesetzt sind — in derselben Operations-Batch eine neue Pending-
     * Instanz an. Description/Project/Tags/Priority werden kopiert; Annotations
     * werden bewusst NICHT übertragen, da Annotations zeitpunktbezogen sind.
     * Gibt die UUID der neu erzeugten Folge-Instanz zurück (`None`, wenn keine).
     */
    func markDoneWithFollowup(uuid: String, newDue: Int64?, recur: String?, priority: String?, project: String?, tags: [String], description: String) throws  -> String?
    
    /**
     * Ändert die Beschreibung der Task mit `uuid` und committet.
     */
    func modifyDescription(uuid: String, newDescription: String) throws 
    
    /**
     * Gibt die Anzahl der lokalen Operationen zurück, die noch nicht mit dem Server
     * synchronisiert wurden. Wird vom Sync-Toolbar-Counter der App genutzt.
     *
     * `usize` aus taskchampion wird als `u64` zurückgegeben, da UniFFI den Typ `usize`
     * nicht direkt abbilden kann. Auf 64-bit-macOS (und 32-bit-Targets) ist der Cast
     * verlustfrei aufwärts.
     */
    func numLocalOperations() throws  -> UInt64
    
    /**
     * Reaktiviert einen Task: Status zurück auf Pending. Aufgerufen z.B., wenn
     * User einen versehentlich erledigten Task wiederherstellen will.
     */
    func reactivate(uuid: String) throws 
    
    /**
     * Entfernt die Annotation mit dem gegebenen Entry-Zeitstempel (Unix-Sekunden).
     * Wird vom Detail-Editor zum Löschen einzelner Annotations genutzt.
     */
    func removeAnnotation(uuid: String, entry: Int64) throws 
    
    /**
     * Entfernt einen User-Tag. No-op, falls der Tag nicht existiert.
     */
    func removeTag(uuid: String, tag: String) throws 
    
    /**
     * Setzt das `due`-Property (Unix-Sekunden). `None` entfernt die Fälligkeit.
     */
    func setDue(uuid: String, due: Int64?) throws 
    
    /**
     * Setzt das `priority`-Property (`H` / `M` / `L`). `None` oder leerer String
     * entfernt es. Es wird nicht validiert — Taskwarrior toleriert beliebige
     * Strings, sortiert aber clientseitig nach diesem Wert.
     */
    func setPriority(uuid: String, priority: String?) throws 
    
    /**
     * Setzt das `project`-Property. `None` oder leerer String entfernt es.
     */
    func setProject(uuid: String, project: String?) throws 
    
    /**
     * Setzt das `recur`-Property (z.B. `daily`, `weekly`, `1d`, `2w`). `None` oder
     * leerer String entfernen es. Wird app-seitig interpretiert — TaskChampion-Lib
     * generiert keine Children automatisch.
     */
    func setRecur(uuid: String, recur: String?) throws 
    
    /**
     * Setzt das `scheduled`-Property (Start-Datum als Unix-Sekunden). `None`
     * entfernt es. Tasks mit `scheduled` in der Zukunft gelten App-seitig als
     * „geplant".
     */
    func setScheduled(uuid: String, scheduled: Int64?) throws 
    
    /**
     * Setzt das `wait`-Property (Unix-Sekunden). `None` entfernt es. Tasks mit
     * `wait` in der Zukunft gelten als „wartend" (Snooze).
     */
    func setWait(uuid: String, wait: Int64?) throws 
    
    /**
     * Synchronisiert die Replica gegen einen TaskChampion-Sync-Server.
     * `client_id` muss ein UUID-String sein. `encryption_secret` wird als UTF-8-Bytes verwendet.
     */
    func sync(serverUrl: String, clientId: String, encryptionSecret: String) throws 
    
    /**
     * Aktualisiert Metadaten eines bestehenden Tasks in einer einzigen Commit-Batch:
     * Description, project (None = clear), Tags (komplette Ersetzung), due (None = clear).
     * Verwendet vom Reparatur-Lauf, der Legacy-Tasks (`+tag` / `project:foo` in der
     * Description als Text) in saubere Properties überführt.
     */
    func updateTaskMetadata(uuid: String, description: String, project: String?, tags: [String], due: Int64?) throws 
    
}
open class TaskStore: TaskStoreProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_vergissmeinnicht_core_fn_clone_taskstore(self.pointer, $0) }
    }
    /**
     * Öffnet (oder legt an) eine TaskChampion-SQLite-Replica unter `db_path`.
     * Der Pfad muss ein Verzeichnis sein (TaskChampion legt darin SQLite-Dateien an).
     */
public convenience init(dbPath: String)throws  {
    let pointer =
        try rustCallWithError(FfiConverterTypeVmError_lift) {
    uniffi_vergissmeinnicht_core_fn_constructor_taskstore_new(
        FfiConverterString.lower(dbPath),$0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_vergissmeinnicht_core_fn_free_taskstore(pointer, $0) }
    }

    

    
    /**
     * Hängt eine Annotation an die Task mit `uuid` an. Entry-Zeitstempel = `Utc::now()`.
     */
open func addAnnotation(uuid: String, annotation: String)throws   {try rustCallWithError(FfiConverterTypeVmError_lift) {
    uniffi_vergissmeinnicht_core_fn_method_taskstore_add_annotation(self.uniffiClonePointer(),
        FfiConverterString.lower(uuid),
        FfiConverterString.lower(annotation),$0
    )
}
}
    
    /**
     * Fügt einen einzelnen User-Tag hinzu. No-op, falls der Tag bereits existiert.
     */
open func addTag(uuid: String, tag: String)throws   {try rustCallWithError(FfiConverterTypeVmError_lift) {
    uniffi_vergissmeinnicht_core_fn_method_taskstore_add_tag(self.uniffiClonePointer(),
        FfiConverterString.lower(uuid),
        FfiConverterString.lower(tag),$0
    )
}
}
    
    /**
     * Legt einen neuen Task mit der gegebenen Description an und gibt seine UUID zurück.
     */
open func addTask(description: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeVmError_lift) {
    uniffi_vergissmeinnicht_core_fn_method_taskstore_add_task(self.uniffiClonePointer(),
        FfiConverterString.lower(description),$0
    )
})
}
    
    /**
     * Legt einen neuen Task mit voller Metadaten-Persistierung an: project (raw value),
     * User-Tags und due (Unix-Sekunden). Leere Tags und None/Empty-Project werden
     * nicht geschrieben. Tag-Strings müssen TaskChampion-konform sein
     * (kein Whitespace, kein Operator-Zeichen am Anfang, kein Doppelpunkt darin).
     */
open func addTaskFull(description: String, project: String?, tags: [String], due: Int64?)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeVmError_lift) {
    uniffi_vergissmeinnicht_core_fn_method_taskstore_add_task_full(self.uniffiClonePointer(),
        FfiConverterString.lower(description),
        FfiConverterOptionString.lower(project),
        FfiConverterSequenceString.lower(tags),
        FfiConverterOptionInt64.lower(due),$0
    )
})
}
    
    /**
     * Markiert die Task mit `uuid` als gelöscht (`Status::Deleted`) und committet.
     * Das Operations-Log bleibt erhalten — kein Purge.
     */
open func deleteTask(uuid: String)throws   {try rustCallWithError(FfiConverterTypeVmError_lift) {
    uniffi_vergissmeinnicht_core_fn_method_taskstore_delete_task(self.uniffiClonePointer(),
        FfiConverterString.lower(uuid),$0
    )
}
}
    
    /**
     * Backwards-Compat-Alias für die App: nur Pending, mit Working-Set-IDs.
     */
open func listPending()throws  -> [TaskInfo]  {
    return try  FfiConverterSequenceTypeTaskInfo.lift(try rustCallWithError(FfiConverterTypeVmError_lift) {
    uniffi_vergissmeinnicht_core_fn_method_taskstore_list_pending(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Listet alle Tasks (Pending oder optional auch Completed/Recurring).
     * Deleted-Tasks bleiben immer aussen vor.
     *
     * Bei `include_completed = false` wird nur das Working Set durchlaufen — das enthält
     * ausschließlich Pending-Tasks. Recurring-Master und Completed bleiben in diesem
     * Modus unsichtbar; wer sie braucht, muss `include_completed = true` setzen.
     * Bei `true` werden Pending mit `working_set_id` zuerst ausgegeben, danach alle
     * übrigen sichtbaren Status (Completed, Recurring, sowie ggf. Pending ohne
     * Working-Set-Eintrag) — die App sortiert clientseitig.
     */
open func listTasks(includeCompleted: Bool)throws  -> [TaskInfo]  {
    return try  FfiConverterSequenceTypeTaskInfo.lift(try rustCallWithError(FfiConverterTypeVmError_lift) {
    uniffi_vergissmeinnicht_core_fn_method_taskstore_list_tasks(self.uniffiClonePointer(),
        FfiConverterBool.lower(includeCompleted),$0
    )
})
}
    
    /**
     * Markiert die Task mit `uuid` als erledigt (`Status::Completed`) und committet.
     */
open func markDone(uuid: String)throws   {try rustCallWithError(FfiConverterTypeVmError_lift) {
    uniffi_vergissmeinnicht_core_fn_method_taskstore_mark_done(self.uniffiClonePointer(),
        FfiConverterString.lower(uuid),$0
    )
}
}
    
    /**
     * Markiert eine Pending-Task als erledigt und legt — sofern `recur` und
     * `new_due` gesetzt sind — in derselben Operations-Batch eine neue Pending-
     * Instanz an. Description/Project/Tags/Priority werden kopiert; Annotations
     * werden bewusst NICHT übertragen, da Annotations zeitpunktbezogen sind.
     * Gibt die UUID der neu erzeugten Folge-Instanz zurück (`None`, wenn keine).
     */
open func markDoneWithFollowup(uuid: String, newDue: Int64?, recur: String?, priority: String?, project: String?, tags: [String], description: String)throws  -> String?  {
    return try  FfiConverterOptionString.lift(try rustCallWithError(FfiConverterTypeVmError_lift) {
    uniffi_vergissmeinnicht_core_fn_method_taskstore_mark_done_with_followup(self.uniffiClonePointer(),
        FfiConverterString.lower(uuid),
        FfiConverterOptionInt64.lower(newDue),
        FfiConverterOptionString.lower(recur),
        FfiConverterOptionString.lower(priority),
        FfiConverterOptionString.lower(project),
        FfiConverterSequenceString.lower(tags),
        FfiConverterString.lower(description),$0
    )
})
}
    
    /**
     * Ändert die Beschreibung der Task mit `uuid` und committet.
     */
open func modifyDescription(uuid: String, newDescription: String)throws   {try rustCallWithError(FfiConverterTypeVmError_lift) {
    uniffi_vergissmeinnicht_core_fn_method_taskstore_modify_description(self.uniffiClonePointer(),
        FfiConverterString.lower(uuid),
        FfiConverterString.lower(newDescription),$0
    )
}
}
    
    /**
     * Gibt die Anzahl der lokalen Operationen zurück, die noch nicht mit dem Server
     * synchronisiert wurden. Wird vom Sync-Toolbar-Counter der App genutzt.
     *
     * `usize` aus taskchampion wird als `u64` zurückgegeben, da UniFFI den Typ `usize`
     * nicht direkt abbilden kann. Auf 64-bit-macOS (und 32-bit-Targets) ist der Cast
     * verlustfrei aufwärts.
     */
open func numLocalOperations()throws  -> UInt64  {
    return try  FfiConverterUInt64.lift(try rustCallWithError(FfiConverterTypeVmError_lift) {
    uniffi_vergissmeinnicht_core_fn_method_taskstore_num_local_operations(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Reaktiviert einen Task: Status zurück auf Pending. Aufgerufen z.B., wenn
     * User einen versehentlich erledigten Task wiederherstellen will.
     */
open func reactivate(uuid: String)throws   {try rustCallWithError(FfiConverterTypeVmError_lift) {
    uniffi_vergissmeinnicht_core_fn_method_taskstore_reactivate(self.uniffiClonePointer(),
        FfiConverterString.lower(uuid),$0
    )
}
}
    
    /**
     * Entfernt die Annotation mit dem gegebenen Entry-Zeitstempel (Unix-Sekunden).
     * Wird vom Detail-Editor zum Löschen einzelner Annotations genutzt.
     */
open func removeAnnotation(uuid: String, entry: Int64)throws   {try rustCallWithError(FfiConverterTypeVmError_lift) {
    uniffi_vergissmeinnicht_core_fn_method_taskstore_remove_annotation(self.uniffiClonePointer(),
        FfiConverterString.lower(uuid),
        FfiConverterInt64.lower(entry),$0
    )
}
}
    
    /**
     * Entfernt einen User-Tag. No-op, falls der Tag nicht existiert.
     */
open func removeTag(uuid: String, tag: String)throws   {try rustCallWithError(FfiConverterTypeVmError_lift) {
    uniffi_vergissmeinnicht_core_fn_method_taskstore_remove_tag(self.uniffiClonePointer(),
        FfiConverterString.lower(uuid),
        FfiConverterString.lower(tag),$0
    )
}
}
    
    /**
     * Setzt das `due`-Property (Unix-Sekunden). `None` entfernt die Fälligkeit.
     */
open func setDue(uuid: String, due: Int64?)throws   {try rustCallWithError(FfiConverterTypeVmError_lift) {
    uniffi_vergissmeinnicht_core_fn_method_taskstore_set_due(self.uniffiClonePointer(),
        FfiConverterString.lower(uuid),
        FfiConverterOptionInt64.lower(due),$0
    )
}
}
    
    /**
     * Setzt das `priority`-Property (`H` / `M` / `L`). `None` oder leerer String
     * entfernt es. Es wird nicht validiert — Taskwarrior toleriert beliebige
     * Strings, sortiert aber clientseitig nach diesem Wert.
     */
open func setPriority(uuid: String, priority: String?)throws   {try rustCallWithError(FfiConverterTypeVmError_lift) {
    uniffi_vergissmeinnicht_core_fn_method_taskstore_set_priority(self.uniffiClonePointer(),
        FfiConverterString.lower(uuid),
        FfiConverterOptionString.lower(priority),$0
    )
}
}
    
    /**
     * Setzt das `project`-Property. `None` oder leerer String entfernt es.
     */
open func setProject(uuid: String, project: String?)throws   {try rustCallWithError(FfiConverterTypeVmError_lift) {
    uniffi_vergissmeinnicht_core_fn_method_taskstore_set_project(self.uniffiClonePointer(),
        FfiConverterString.lower(uuid),
        FfiConverterOptionString.lower(project),$0
    )
}
}
    
    /**
     * Setzt das `recur`-Property (z.B. `daily`, `weekly`, `1d`, `2w`). `None` oder
     * leerer String entfernen es. Wird app-seitig interpretiert — TaskChampion-Lib
     * generiert keine Children automatisch.
     */
open func setRecur(uuid: String, recur: String?)throws   {try rustCallWithError(FfiConverterTypeVmError_lift) {
    uniffi_vergissmeinnicht_core_fn_method_taskstore_set_recur(self.uniffiClonePointer(),
        FfiConverterString.lower(uuid),
        FfiConverterOptionString.lower(recur),$0
    )
}
}
    
    /**
     * Setzt das `scheduled`-Property (Start-Datum als Unix-Sekunden). `None`
     * entfernt es. Tasks mit `scheduled` in der Zukunft gelten App-seitig als
     * „geplant".
     */
open func setScheduled(uuid: String, scheduled: Int64?)throws   {try rustCallWithError(FfiConverterTypeVmError_lift) {
    uniffi_vergissmeinnicht_core_fn_method_taskstore_set_scheduled(self.uniffiClonePointer(),
        FfiConverterString.lower(uuid),
        FfiConverterOptionInt64.lower(scheduled),$0
    )
}
}
    
    /**
     * Setzt das `wait`-Property (Unix-Sekunden). `None` entfernt es. Tasks mit
     * `wait` in der Zukunft gelten als „wartend" (Snooze).
     */
open func setWait(uuid: String, wait: Int64?)throws   {try rustCallWithError(FfiConverterTypeVmError_lift) {
    uniffi_vergissmeinnicht_core_fn_method_taskstore_set_wait(self.uniffiClonePointer(),
        FfiConverterString.lower(uuid),
        FfiConverterOptionInt64.lower(wait),$0
    )
}
}
    
    /**
     * Synchronisiert die Replica gegen einen TaskChampion-Sync-Server.
     * `client_id` muss ein UUID-String sein. `encryption_secret` wird als UTF-8-Bytes verwendet.
     */
open func sync(serverUrl: String, clientId: String, encryptionSecret: String)throws   {try rustCallWithError(FfiConverterTypeVmError_lift) {
    uniffi_vergissmeinnicht_core_fn_method_taskstore_sync(self.uniffiClonePointer(),
        FfiConverterString.lower(serverUrl),
        FfiConverterString.lower(clientId),
        FfiConverterString.lower(encryptionSecret),$0
    )
}
}
    
    /**
     * Aktualisiert Metadaten eines bestehenden Tasks in einer einzigen Commit-Batch:
     * Description, project (None = clear), Tags (komplette Ersetzung), due (None = clear).
     * Verwendet vom Reparatur-Lauf, der Legacy-Tasks (`+tag` / `project:foo` in der
     * Description als Text) in saubere Properties überführt.
     */
open func updateTaskMetadata(uuid: String, description: String, project: String?, tags: [String], due: Int64?)throws   {try rustCallWithError(FfiConverterTypeVmError_lift) {
    uniffi_vergissmeinnicht_core_fn_method_taskstore_update_task_metadata(self.uniffiClonePointer(),
        FfiConverterString.lower(uuid),
        FfiConverterString.lower(description),
        FfiConverterOptionString.lower(project),
        FfiConverterSequenceString.lower(tags),
        FfiConverterOptionInt64.lower(due),$0
    )
}
}
    

}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTaskStore: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = TaskStore

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> TaskStore {
        return TaskStore(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: TaskStore) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TaskStore {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: TaskStore, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTaskStore_lift(_ pointer: UnsafeMutableRawPointer) throws -> TaskStore {
    return try FfiConverterTypeTaskStore.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTaskStore_lower(_ value: TaskStore) -> UnsafeMutableRawPointer {
    return FfiConverterTypeTaskStore.lower(value)
}




public struct AnnotationInfo {
    /**
     * Entry-Zeitpunkt der Annotation als Unix-Sekunden (i64). Dient gleichzeitig als
     * Schlüssel beim Entfernen.
     */
    public var entry: Int64
    public var description: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Entry-Zeitpunkt der Annotation als Unix-Sekunden (i64). Dient gleichzeitig als
         * Schlüssel beim Entfernen.
         */entry: Int64, description: String) {
        self.entry = entry
        self.description = description
    }
}

#if compiler(>=6)
extension AnnotationInfo: Sendable {}
#endif


extension AnnotationInfo: Equatable, Hashable {
    public static func ==(lhs: AnnotationInfo, rhs: AnnotationInfo) -> Bool {
        if lhs.entry != rhs.entry {
            return false
        }
        if lhs.description != rhs.description {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(entry)
        hasher.combine(description)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAnnotationInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AnnotationInfo {
        return
            try AnnotationInfo(
                entry: FfiConverterInt64.read(from: &buf), 
                description: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: AnnotationInfo, into buf: inout [UInt8]) {
        FfiConverterInt64.write(value.entry, into: &buf)
        FfiConverterString.write(value.description, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAnnotationInfo_lift(_ buf: RustBuffer) throws -> AnnotationInfo {
    return try FfiConverterTypeAnnotationInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAnnotationInfo_lower(_ value: AnnotationInfo) -> RustBuffer {
    return FfiConverterTypeAnnotationInfo.lower(value)
}


public struct TaskInfo {
    public var uuid: String
    public var description: String
    /**
     * Wert der `project`-Property; leer falls nicht gesetzt.
     */
    public var project: String?
    /**
     * User-Tags (synthetische TaskChampion-Tags wie PENDING/OVERDUE sind herausgefiltert).
     */
    public var tags: [String]
    /**
     * Due-Date als Unix-Sekunden (i64). UniFFI bildet `Option<chrono::DateTime>` nicht direkt
     * auf Swift ab; der i64-Pfad ist robust und auf Swift-Seite via `Date(timeIntervalSince1970:)`
     * trivial konvertierbar.
     */
    public var due: Int64?
    /**
     * Status des Tasks (pending / completed / deleted).
     */
    public var status: TaskStatus
    /**
     * Entry-Zeitpunkt der Task (Anlage-Datum) als Unix-Sekunden. Wird beim Anlegen gesetzt.
     */
    public var entry: Int64?
    /**
     * Working-Set-ID (Taskwarrior-typische numerische ID, 1-N). Nur für Pending-Tasks
     * definiert; für Completed/Deleted ist `None`.
     */
    public var workingSetId: UInt32?
    /**
     * Priority-Property als Rohwert (typisch `H` / `M` / `L`); nicht validiert.
     */
    public var priority: String?
    /**
     * Annotations zum Task, in beliebiger Reihenfolge.
     */
    public var annotations: [AnnotationInfo]
    /**
     * Wait-Property (Snooze) als Unix-Sekunden. Liegt ein Wert in der Zukunft,
     * gilt der Task als „wartend" — Taskwarrior versteckt solche Tasks per Default
     * aus `task list`; die App zeigt sie in einer eigenen Sidebar-Sektion.
     */
    public var wait: Int64?
    /**
     * Recur-Property als Rohstring (z.B. `daily`, `weekly`, `monthly`, `1d`, `2w`).
     * Wir interpretieren es App-seitig — TaskChampion-Lib generiert keine Children.
     */
    public var recur: String?
    /**
     * Scheduled-Property (Start-Datum / Defer-Until) als Unix-Sekunden. Tasks mit
     * `scheduled` in der Zukunft sind „geplant" und werden aus ToDo/Inbox/Überfällig
     * ausgeblendet, bis das Datum erreicht ist.
     */
    public var scheduled: Int64?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(uuid: String, description: String, 
        /**
         * Wert der `project`-Property; leer falls nicht gesetzt.
         */project: String?, 
        /**
         * User-Tags (synthetische TaskChampion-Tags wie PENDING/OVERDUE sind herausgefiltert).
         */tags: [String], 
        /**
         * Due-Date als Unix-Sekunden (i64). UniFFI bildet `Option<chrono::DateTime>` nicht direkt
         * auf Swift ab; der i64-Pfad ist robust und auf Swift-Seite via `Date(timeIntervalSince1970:)`
         * trivial konvertierbar.
         */due: Int64?, 
        /**
         * Status des Tasks (pending / completed / deleted).
         */status: TaskStatus, 
        /**
         * Entry-Zeitpunkt der Task (Anlage-Datum) als Unix-Sekunden. Wird beim Anlegen gesetzt.
         */entry: Int64?, 
        /**
         * Working-Set-ID (Taskwarrior-typische numerische ID, 1-N). Nur für Pending-Tasks
         * definiert; für Completed/Deleted ist `None`.
         */workingSetId: UInt32?, 
        /**
         * Priority-Property als Rohwert (typisch `H` / `M` / `L`); nicht validiert.
         */priority: String?, 
        /**
         * Annotations zum Task, in beliebiger Reihenfolge.
         */annotations: [AnnotationInfo], 
        /**
         * Wait-Property (Snooze) als Unix-Sekunden. Liegt ein Wert in der Zukunft,
         * gilt der Task als „wartend" — Taskwarrior versteckt solche Tasks per Default
         * aus `task list`; die App zeigt sie in einer eigenen Sidebar-Sektion.
         */wait: Int64?, 
        /**
         * Recur-Property als Rohstring (z.B. `daily`, `weekly`, `monthly`, `1d`, `2w`).
         * Wir interpretieren es App-seitig — TaskChampion-Lib generiert keine Children.
         */recur: String?, 
        /**
         * Scheduled-Property (Start-Datum / Defer-Until) als Unix-Sekunden. Tasks mit
         * `scheduled` in der Zukunft sind „geplant" und werden aus ToDo/Inbox/Überfällig
         * ausgeblendet, bis das Datum erreicht ist.
         */scheduled: Int64?) {
        self.uuid = uuid
        self.description = description
        self.project = project
        self.tags = tags
        self.due = due
        self.status = status
        self.entry = entry
        self.workingSetId = workingSetId
        self.priority = priority
        self.annotations = annotations
        self.wait = wait
        self.recur = recur
        self.scheduled = scheduled
    }
}

#if compiler(>=6)
extension TaskInfo: Sendable {}
#endif


extension TaskInfo: Equatable, Hashable {
    public static func ==(lhs: TaskInfo, rhs: TaskInfo) -> Bool {
        if lhs.uuid != rhs.uuid {
            return false
        }
        if lhs.description != rhs.description {
            return false
        }
        if lhs.project != rhs.project {
            return false
        }
        if lhs.tags != rhs.tags {
            return false
        }
        if lhs.due != rhs.due {
            return false
        }
        if lhs.status != rhs.status {
            return false
        }
        if lhs.entry != rhs.entry {
            return false
        }
        if lhs.workingSetId != rhs.workingSetId {
            return false
        }
        if lhs.priority != rhs.priority {
            return false
        }
        if lhs.annotations != rhs.annotations {
            return false
        }
        if lhs.wait != rhs.wait {
            return false
        }
        if lhs.recur != rhs.recur {
            return false
        }
        if lhs.scheduled != rhs.scheduled {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(uuid)
        hasher.combine(description)
        hasher.combine(project)
        hasher.combine(tags)
        hasher.combine(due)
        hasher.combine(status)
        hasher.combine(entry)
        hasher.combine(workingSetId)
        hasher.combine(priority)
        hasher.combine(annotations)
        hasher.combine(wait)
        hasher.combine(recur)
        hasher.combine(scheduled)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTaskInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TaskInfo {
        return
            try TaskInfo(
                uuid: FfiConverterString.read(from: &buf), 
                description: FfiConverterString.read(from: &buf), 
                project: FfiConverterOptionString.read(from: &buf), 
                tags: FfiConverterSequenceString.read(from: &buf), 
                due: FfiConverterOptionInt64.read(from: &buf), 
                status: FfiConverterTypeTaskStatus.read(from: &buf), 
                entry: FfiConverterOptionInt64.read(from: &buf), 
                workingSetId: FfiConverterOptionUInt32.read(from: &buf), 
                priority: FfiConverterOptionString.read(from: &buf), 
                annotations: FfiConverterSequenceTypeAnnotationInfo.read(from: &buf), 
                wait: FfiConverterOptionInt64.read(from: &buf), 
                recur: FfiConverterOptionString.read(from: &buf), 
                scheduled: FfiConverterOptionInt64.read(from: &buf)
        )
    }

    public static func write(_ value: TaskInfo, into buf: inout [UInt8]) {
        FfiConverterString.write(value.uuid, into: &buf)
        FfiConverterString.write(value.description, into: &buf)
        FfiConverterOptionString.write(value.project, into: &buf)
        FfiConverterSequenceString.write(value.tags, into: &buf)
        FfiConverterOptionInt64.write(value.due, into: &buf)
        FfiConverterTypeTaskStatus.write(value.status, into: &buf)
        FfiConverterOptionInt64.write(value.entry, into: &buf)
        FfiConverterOptionUInt32.write(value.workingSetId, into: &buf)
        FfiConverterOptionString.write(value.priority, into: &buf)
        FfiConverterSequenceTypeAnnotationInfo.write(value.annotations, into: &buf)
        FfiConverterOptionInt64.write(value.wait, into: &buf)
        FfiConverterOptionString.write(value.recur, into: &buf)
        FfiConverterOptionInt64.write(value.scheduled, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTaskInfo_lift(_ buf: RustBuffer) throws -> TaskInfo {
    return try FfiConverterTypeTaskInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTaskInfo_lower(_ value: TaskInfo) -> RustBuffer {
    return FfiConverterTypeTaskInfo.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum TaskStatus {
    
    case pending
    case completed
    case deleted
    case recurring
}


#if compiler(>=6)
extension TaskStatus: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTaskStatus: FfiConverterRustBuffer {
    typealias SwiftType = TaskStatus

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TaskStatus {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .pending
        
        case 2: return .completed
        
        case 3: return .deleted
        
        case 4: return .recurring
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: TaskStatus, into buf: inout [UInt8]) {
        switch value {
        
        
        case .pending:
            writeInt(&buf, Int32(1))
        
        
        case .completed:
            writeInt(&buf, Int32(2))
        
        
        case .deleted:
            writeInt(&buf, Int32(3))
        
        
        case .recurring:
            writeInt(&buf, Int32(4))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTaskStatus_lift(_ buf: RustBuffer) throws -> TaskStatus {
    return try FfiConverterTypeTaskStatus.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTaskStatus_lower(_ value: TaskStatus) -> RustBuffer {
    return FfiConverterTypeTaskStatus.lower(value)
}


extension TaskStatus: Equatable, Hashable {}







public enum VmError: Swift.Error {

    
    
    case Storage(msg: String
    )
    case Conversion(msg: String
    )
    case NotFound(uuid: String
    )
    case Sync(msg: String
    )
    case Internal(msg: String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeVmError: FfiConverterRustBuffer {
    typealias SwiftType = VmError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> VmError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Storage(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 2: return .Conversion(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 3: return .NotFound(
            uuid: try FfiConverterString.read(from: &buf)
            )
        case 4: return .Sync(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 5: return .Internal(
            msg: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: VmError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .Storage(msg):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .Conversion(msg):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .NotFound(uuid):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(uuid, into: &buf)
            
        
        case let .Sync(msg):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .Internal(msg):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(msg, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVmError_lift(_ buf: RustBuffer) throws -> VmError {
    return try FfiConverterTypeVmError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVmError_lower(_ value: VmError) -> RustBuffer {
    return FfiConverterTypeVmError.lower(value)
}


extension VmError: Equatable, Hashable {}




extension VmError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt32: FfiConverterRustBuffer {
    typealias SwiftType = UInt32?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt32.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt32.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionInt64: FfiConverterRustBuffer {
    typealias SwiftType = Int64?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterInt64.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterInt64.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeAnnotationInfo: FfiConverterRustBuffer {
    typealias SwiftType = [AnnotationInfo]

    public static func write(_ value: [AnnotationInfo], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeAnnotationInfo.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [AnnotationInfo] {
        let len: Int32 = try readInt(&buf)
        var seq = [AnnotationInfo]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeAnnotationInfo.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeTaskInfo: FfiConverterRustBuffer {
    typealias SwiftType = [TaskInfo]

    public static func write(_ value: [TaskInfo], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeTaskInfo.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [TaskInfo] {
        let len: Int32 = try readInt(&buf)
        var seq = [TaskInfo]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeTaskInfo.read(from: &buf))
        }
        return seq
    }
}
public func ping() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_vergissmeinnicht_core_fn_func_ping($0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 29
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_vergissmeinnicht_core_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_vergissmeinnicht_core_checksum_func_ping() != 12489) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vergissmeinnicht_core_checksum_method_taskstore_add_annotation() != 16896) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vergissmeinnicht_core_checksum_method_taskstore_add_tag() != 42420) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vergissmeinnicht_core_checksum_method_taskstore_add_task() != 25883) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vergissmeinnicht_core_checksum_method_taskstore_add_task_full() != 4153) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vergissmeinnicht_core_checksum_method_taskstore_delete_task() != 18758) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vergissmeinnicht_core_checksum_method_taskstore_list_pending() != 3320) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vergissmeinnicht_core_checksum_method_taskstore_list_tasks() != 33535) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vergissmeinnicht_core_checksum_method_taskstore_mark_done() != 54635) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vergissmeinnicht_core_checksum_method_taskstore_mark_done_with_followup() != 55075) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vergissmeinnicht_core_checksum_method_taskstore_modify_description() != 10881) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vergissmeinnicht_core_checksum_method_taskstore_num_local_operations() != 5356) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vergissmeinnicht_core_checksum_method_taskstore_reactivate() != 43078) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vergissmeinnicht_core_checksum_method_taskstore_remove_annotation() != 19111) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vergissmeinnicht_core_checksum_method_taskstore_remove_tag() != 3845) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vergissmeinnicht_core_checksum_method_taskstore_set_due() != 39542) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vergissmeinnicht_core_checksum_method_taskstore_set_priority() != 34575) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vergissmeinnicht_core_checksum_method_taskstore_set_project() != 48540) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vergissmeinnicht_core_checksum_method_taskstore_set_recur() != 13383) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vergissmeinnicht_core_checksum_method_taskstore_set_scheduled() != 11085) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vergissmeinnicht_core_checksum_method_taskstore_set_wait() != 31016) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vergissmeinnicht_core_checksum_method_taskstore_sync() != 8453) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vergissmeinnicht_core_checksum_method_taskstore_update_task_metadata() != 4155) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vergissmeinnicht_core_checksum_constructor_taskstore_new() != 10478) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureVergissmeinnichtCoreInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all